### ISSUE TITLE
How to get socat logs

### ISSUE THREAD

**Issue by Akzotus** [baudneo/cync-lan#7]
I've got some of the cync fan controllers and am ready to do my best.
What exactly are socat logs and how do I go about obtaining them?

Full disclosure, I not only have no idea what I'm doing, but am also an idiot. So I apologize in advance.

**Comment by baudneo** [comment]
Before you can start, youll need a way to control DNS on your network. Do you have a pi-hole or use pfsense/opnsense as a firewall?

The way that cync-lan works is by hijacking DNS requests, when a cync device tries to connect to the cync cloud by using a domain name, your local DNS server will tell the cync device to connect to a local IP rather than the cync cloud server. cync-lan basically pretends to be the cync cloud server, enabling local control.

**Comment by Akzotus** [comment]
I've got OpenWRT on my router, so I should be able to hijack any addresses needed. If not, I'll soon find out I suppose.

**Comment by baudneo** [comment]
Alright, if you want to, you could take screenshots of the workflow to get the DNS redirection going. I havent used OWRT for a good 10 years, so I have no clue what DNS backend it uses. 

Can you get the DNS stuff set-up? I have examples for pihole and opnsense [in the docs](https://github.com/baudneo/cync-lan/blob/python/docs/DNS.md).
